eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
server:
  port: 8764
zuul:
  routes:
    service1: /service/**
    service2: /service2/**